---
- name: Test hello world
  hosts: localhost
  vars:
    hostslol:
      - host1
      - host2
      - host3
    ansible_connection: local
  tasks:
    - name: Say hello world
      ansible.builtin.debug:
        msg: test test please work! I'm running this against "{{ item }}".
      loop: "{{ hostslol }}"
